### ISSUE TITLE
Move repo to shadow-cljs org?

### ISSUE THREAD

**Issue by alex-dixon** [shadow-cljs/examples#6]
Mentioned in #5. I think this might provide some officiality and discoverability though shadow-cljs is still in your name, so could see it going either way.

**Comment by thheller** [comment]
Done. Moved to https://github.com/shadow-cljs/examples.

**Comment by thheller** [comment]
Not moving the `shadow-cljs` repo itself because I want it to match the clojars repo and I don't want to change the artifact name just yet given that I'd need to update it in a bajillion places. :P
